# spec/spec_helper.rb

# This file is generated by the `rspec --init` command.
# It is a good idea to add `require 'rspec/expectations'` here.

RSpec.configure do |config|
  # Enables the `:focus` filter, allowing you to run only focused tests.
  config.filter_run_when_matching :focus

  # Run all examples in random order to surface order dependencies.
  config.order = :random

  # Print the seed used for random ordering.
  Kernel.srand config.seed

  # Enable the expectation syntax for more readable tests.
  config.expect_with :rspec do |c|
    c.syntax = :expect
  end

  # Enable the mock framework.
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  # Disable RSpec's monkey patching of Kernel and Object.
  config.disable_monkey_patching!

  # Enable the use of `let` and `subject` outside of `describe` blocks.
  config.include RSpec::Mocks::ExampleMethods

  # Additional configurations can go here.
end
